[package]
name = "mtg-cardbase"
version.workspace = true
edition.workspace = true

[dependencies]
arrayvec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
